### ISSUE TITLE
Improve PhoneGap Desktop Documentation

### ISSUE THREAD

**Issue by hermwong** [phonegap/phonegap-docs#167]
- FAQs
 - questions & answers to the most common issues encountered
 - can't connect with Developer App
 - network / firewall related issues

- Technical Troubleshooting
 - technical how to guides (e.g. - reset Desktop's local storage, reset Desktop's template cache)

- Compatibility Chart
 - perhaps a matrix of  versions of Desktop & Developer App that will work with each other (had a few cases where people running iOS 6 version of Developer App trying to connect to Desktop 0.2.X when that particular version of Developer was too old and not compatible)

**Comment by jessemonroy650** [comment]
@hermwong 
My plan was always to include the Phonegap team in this blog post. All my work is on Linux, so I had no idea what PDA did. It took me a while to figure it out. After a recent update to the docs, it was clear what the purpose was.

However, after some time of answering THE SAME questions, it became apparent what the issue was. I open this trouble ticket months ago. If you see the comments, you can see the almost daily confusion. [https://github.com/phonegap/phonegap-docs/issues/137 Format of STEP 5 is confusing for persons with *English as a second language* #137 ]

Even after changes the issue continue. If you look at this document in RAW format you'll see the evolution of comments I keep making on this subject: [https://github.com/jessemonroy650/top-phonegap-mistakes/blob/master/dontUseDesktopApp.md Don't use Desktop App]

To be clear, many, many developers are unaware of the difference between CLI and BUILD, let alone PDA. I like the idea, but it is clear that the only purpose of PDA is to bash the developer over the head in an effort to say "this only requires HTML, CSS and Javascript!"

On this last point, my belief is that many many developers (including seasoned developers) are left incredulous that any framework could accomplish this task. Mind you, I've been programming for 20+ years and at times I can't believe this works.

**Comment by jessemonroy650** [comment]
@hermwong
Based on the confusion _Desktop App_ causes in the other forums, I recommend it have it's own forum. 

Here is the first draft of the blog post. Persons on Nitobi and Google Groups are helping with this as well. [Phonegap Desktop App - What it is and is not](https://unbot.wordpress.com/?p=457&shareadraft=5716d98464be5)

Jesse

**Comment by GarthDB** [comment]
Going back to the original purpose of the issue, I broke this one out into separate, more specific issues.

- https://github.com/phonegap/phonegap-docs/issues/215
- https://github.com/phonegap/phonegap-docs/issues/216
- https://github.com/phonegap/phonegap-docs/issues/217

@jessemonroy650 I heard you were contacted on another channel about your blog post feedback request. If you need anything else feel free to [discuss it on the forum](https://forums.adobe.com/community/phonegap) or open a new issue.
