### ISSUE TITLE
OnAppExit event missing. 

### ISSUE THREAD

**Issue by shahidj** [phonegap/phonegap-docs#179]
We can't track when a phonegap app is going to exit completely from memory. There must be an event to track this functionality like onpause and onresume events. I am looking forward for your kind response with a new release having this functionality.

**Comment by macdonst** [comment]
@shahidj As far as I know there is no way to detect this event in iOS nor Android.

**Comment by shahidj** [comment]
We have a complete lifecycle for each iOS and Android app.  we have those exit app events in Android and iOS.

For your kind information.

In Android 
[onDestroy](http://developer.android.com/reference/android/app/Activity.html#onDestroy())

in iOS 

[applicationWillTerminate](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/applicationWillTerminate:)

or 
[/applicationDidEnterBackground:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/applicationDidEnterBackground:)

Hopefully, it will be helpful for you.

**Comment by macdonst** [comment]
@shahidj right but since I'm not an idiot and I kinda know what I'm talking about on most days you will see that when it comes to `onDestroy` the Android docs that you linked to specifically say:

> There are situations where the system will simply kill the activity's hosting process without calling this method

So that is not a reliable way of knowing when your app exits.

As for iOS if you read this section on [App Termination](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html#//apple_ref/doc/uid/TP40007072-CH2-SW7) you will see:

> 
> Suspended apps receive no notification when they are terminated; the system kills the process and reclaims the corresponding memory. If an app is currently running in the background and not suspended, the system calls the applicationWillTerminate: of its app delegate prior to termination. The system does not call this method when the device reboots.
> 
> In addition to the system terminating your app, the user can terminate your app explicitly using the multitasking UI. User-initiated termination has the same effect as terminating a suspended app. The app’s process is killed and no notification is sent to the app.

So again, not a reliable way of knowing when you app is killed by iOS. 

This is why we can't have nice things. In both cases the OS can swoop in, kill the app and not tell anyone. This is why I said there is no way to do this. What I should have said is there is not way to detect this situation 100% of the time so it doesn't make sense to implement it.

**Comment by shahidj** [comment]
Okay. 
I have an ios app which keep running when it goes in background. It doesn't suspend. Kindly suggest me about the options how to detect the exit app state?

**Comment by GarthDB** [comment]
@shahidj if you are still having issues, please start a discussion on the [forums](https://forums.adobe.com/community/phonegap). If you find a solution and think the content should be added to the docs feel free to open a pull request or a new issue.
