### ISSUE TITLE
Confused with updates - Need a bit of explanation please

### ISSUE THREAD

**Issue by FreddyCrugger** [phonegap/phonegap-docs#301]
Hello,

I find the Phonegap website very confusing.

To update Phonegap we should run this command:
npm install -g phonegap

The version I get is:
8.0.0

But, on this website it shows 8.1.1
https://cordova.apache.org/news/2018/09/27/cordova-cli-8.1.1.html

Why this version is not included in the npm install -g phonegap command?

The other issue I have is that the package.json is updated to  "cordova-android": "^7.0.0"

But on this website is shows that the latest version is 7.1.0
https://cordova.apache.org/announcements/2018/02/26/cordova-android-7.1.0.html

Could someone please explain to me how does all of this works as I am more and more confused about Phonegap.

Thank you.

ps:I have tried with the Node version 8.12, same issue.

**Comment by purplecabbage** [comment]
cordova tooling, phonegap tooling, and the platform cordova-android each have their own versions.

**re: tooling**
Cordova tooling might be updated, for example going from 8.0.0->8.1.0->8.1.1, however PhoneGap still has a dependency on 8.0.0 ... Everything does not always get updated at the same time.

**re: platform updates**
When you added cordova-android to your project, the version was probably 7.0.0, and since then a newer version has come out.  This does not update your project magically.  If you want to update to the latest version of cordova-android, you can do
`phonegap platform rm android`
`phonegap platform add android@7.1.0`

**Comment by FreddyCrugger** [comment]
Thank you so much, great explanation
